### ISSUE TITLE
With a bad dependency configuration, creating actors fails silently

### ISSUE THREAD

**Issue by Teun** [akkadotnet/Akka.DI.AutoFac#15]
I must be doing it wrong, so please point me to any form of documentation or sample.

I have a setup where I create some actors and services they use through DI using Akka.DI.AutoFac. Works fine. However as I try to create a test for their behavior, it doesn't quite work the same way.

I create a normal TestKit class. At the start of the test I initialize the container like so: 

        private void setupDi()
        {
            var builder = new Autofac.ContainerBuilder();
            builder.RegisterType<MyActor>();
            var container = builder.Build();
            new AutoFacDependencyResolver(container, Sys);
        }

then when I do:

        var school = Sys.ActorOf(Sys.DI().Props<MyActor>());

It does not throw, I get an IActorRef, but when I sen messages, they do not arrive and also breakpoints in the constructor of MyActor, it never gets hit. 

I must be missing something here...

**Comment by Teun** [comment]
I realize that this report is rather vague. I am setting up a small sample project to clearly reproduce. Up till now, it works completely as expected. I will report here if I find my problem or post a clear repro path. Do not spend effort on reproduction before.

**Comment by Teun** [comment]
Found my problem: I made a mistake in the setup/registration of my actor. MyActor had a parameter on the constructor of type int?. This was not specified to AutoFac. This changes my question:

When I make a mistake in setting up my dependencies, when I forget a dependency or it throws an error when I resolve the type, I would like to get some sort of indication of this. Now I got back a valid IActorRef with a normal path ("akka://test/user/$a"). It is not ActorRefs.Nobody. The only thing I notice is that the messages never reach the actor. Could we make a failure bubble up into the TestKit test? Or log something?

**Comment by Horusiath** [comment]
@Teun you probably received that in logs. If you're using xUnit, in order to bind xunit output to akka.net logging, you need to provide `ITestOutputHelper` value to `Xunit.TestKit` constructor - if you add it as parameter of your own test, xunit should inject it automatically.

```csharp
public class MySpec : Xunit2.TestKit
{
    public MySpec(ITestOutputHelper output) : base(output: output) {}
}
```

**Comment by Teun** [comment]
Ah, that makes all the difference. Thank you very much. Maybe this should appear somewhere in the samples.
