### ISSUE TITLE
Make the container and actorsystem protected in AutoFacDependencyResolver.cs

### ISSUE THREAD

**Issue by netogallo** [akkadotnet/Akka.DI.AutoFac#34]
I need to subclass the AutoFacDependencyResolver, however I am currently unable to use the class as it is given because container and actorsystem are private. So I have to copy the class into my codebase.

**Comment by Danthar** [comment]
What issue are you running into that you need to subclass it?
But i don't mind making it protected. Ill be happy to accept PR's.
