### ISSUE TITLE
Need to add Akka.DependencyInjection support / documentation for Autofac?

### ISSUE THREAD

**Issue by Aaronontheweb** [akkadotnet/Akka.DI.AutoFac#82]
How do we resolve the existence of this plugin with the new approaches we're recommending for DI in Akka.NET v1.4.15 and beyond?

cc @akkadotnet/core

**Comment by Danthar** [comment]
By deprecating it. Like all the other DI framework specific plugins.

**Comment by IgorFedchenko** [comment]
Yeah, since we have deprecated Akka.DI package because of rewriting the whole DI stuff, we probably have to deprecate this plugins as well. And start new `Akka.DependencyInjection.AutoFac` if needed (I doubt that).
